apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oygbejv2d-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oygbejv2d-python 
  name: oygbejv2d-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oygbejv2d-python 
