apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oygbejv2d-python 
  janus-idp.io/tekton: oygbejv2d-python
  backstage.io/kubernetes-id: oygbejv2d-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oygbejv2d-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml